// Generated by CoffeeScript 1.6.3
var config, localConfig, underscore, _;

underscore = require('underscore');

_ = underscore._;

if (!config) {
  localConfig = {
    hostname: 'localhost',
    port: 8000,
    name: 'xebia-mobile-backend',
    uri: ['xebia-notification-backend.helyx.org'],
    mongoConfig: {
      hostname: 'localhost',
      port: 27017
    }
  };
  config = _.extend({}, localConfig);
}

module.exports = {
  confif: config
};
