// Generated by CoffeeScript 1.6.3
var config, localConfig, underscore, _;

underscore = require('underscore');

_ = underscore._;

if (!config) {
  localConfig = {
    hostname: 'localhost',
    port: 9090,
    appname: 'xebia-notification-backend',
    uri: ['xebia-notification-backend.helyx.org'],
    mongo: {
      dbname: 'xebia-notification-backend',
      hostname: 'localhost',
      port: 27017
    }
  };
  config = _.extend({}, localConfig);
}

module.exports = {
  hostname: config.hostname,
  port: config.port,
  appname: config.appname,
  uri: config.uri,
  mongo: config.mongo
};
