// Generated by CoffeeScript 1.6.3
var ensureAuthenticated,
  _this = this;

ensureAuthenticated = function(req, res, next) {
  if (req.isAuthenticated()) {
    return next();
  } else {
    res.redirect('/login');
  }
};

module.exports = {
  ensureAuthenticated: ensureAuthenticated
};
