// Generated by CoffeeScript 1.6.3
var account, authGoogle, authGoogleCallback, login, logout, security, utils,
  _this = this;

utils = require('../lib/utils');

security = require('../lib/security');

account = function(req, res) {
  res.render('account', {
    user: req.user
  });
};

login = function(req, res) {
  res.render('login', {
    user: req.user
  });
};

authGoogle = function(req, res) {
  res.redirect('/');
};

authGoogleCallback = function(req, res) {
  res.redirect('/');
};

logout = function(req, res) {
  req.logout();
  res.redirect('/');
};

module.exports = {
  account: account,
  login: login,
  authGoogle: authGoogle,
  authGoogleCallback: authGoogleCallback,
  logout: logout
};
